export const API_HOST = 'http://shopxeom.local/api/v1';
export const API_LANG = API_HOST + '/lang';
export const API_CHECK_LOGIN = API_HOST + '/check_login';
export const API_HANDLE_LOGIN = API_HOST + '/handle_login';
export const API_LOGOUT = API_HOST + '/logout';
export const API_CONFIG = API_HOST + '/config';
export const API_GETDATA = API_HOST + '/get';
export const API_GETSELECTDATA = API_HOST + '/get_select_data';
export const API_SAVE = API_HOST + '/save';